buildlist:
  - contents/index.yaml
  - contents/leavingforlondon.yaml
  - contents/unsw.yaml
  - contents/placeholder.yaml
  - contents/oxford.yaml
  - contents/cambridge.yaml
  - contents/hamburg.yaml
  - contents/amsterdam.yaml
  - contents/quarantine.yaml
  - contents/zurich.yaml
  - contents/madrid.yaml
  - contents/westbaydorset.yaml
  - contents/dc.yaml
  - contents/perth.yaml
  - contents/melbourne.yaml
  # - contents/saap.yaml
  - contents/sydneyinlockdown.yaml
  - contents/newcastle.yaml
  - contents/daylesford.yaml
  - contents/queenstown.yaml
  - contents/milfordsound.yaml
  - contents/arrowtown.yaml
  - contents/southland.yaml
  - contents/christchurch.yaml
  - contents/wellington.yaml
  - contents/cairns.yaml
  - contents/adelaide.yaml
  - contents/adelaide_hills.yaml

copy:
 - css
 - fonts
