buildlist:
  - contents/index.yaml
  - contents/leavingforlondon.yaml
  - contents/unsw.yaml
  - contents/aboutme.yaml
  - contents/placeholder.yaml
  - contents/oxford.yaml

ignore:
  - contents/placeholder.yaml
  - contents/unsw.yaml
  - contents/quarantine.yaml
  - contents/saap.yaml
  - contents/oxford.yaml
  - contents/cambridge.yaml
  - contents/hamburg.yaml
  - contents/amsterdam.yaml
  - contents/zurich.yaml
  - contents/madrid.yaml
  - contents/westbaydorset.yaml
  - contents/dc.yaml
  - contents/perth.yaml
  - contents/melbourne.yaml
  - contents/aboutme.yaml

copy:
 - css
 - fonts
